<?xml version="1.0"?>
<package format="3">
  <name>delivery_robot_manager</name>
  <version>0.0.1</version>
  <description>Delivery task queue manager with Nav2 action client and nearest-neighbor arbitration</description>
  <maintainer email="you@example.com">student</maintainer>
  <license>Apache-2.0</license>
  <buildtool_depend>ament_python</buildtool_depend>
  <buildtool_depend>rosidl_default_generators</buildtool_depend>
  <exec_depend>rclpy</exec_depend>
  <exec_depend>rclpy_action</exec_depend>
  <exec_depend>nav2_msgs</exec_depend>
  <exec_depend>std_srvs</exec_depend>
  <exec_depend>std_msgs</exec_depend>
  <exec_depend>geometry_msgs</exec_depend>
  <exec_depend>rosidl_default_runtime</exec_depend>
  <member_of_group>rosidl_interface_packages</member_of_group>
  <export><build_type>ament_python</build_type></export>
</package>
