<?xml version="1.0"?>
<package format="3">
  <name>delivery_robot_nav2</name>
  <version>0.0.1</version>
  <description>Nav2 bringup without lidar/map, using RangeSensorLayer + static TF</description>
  <maintainer email="you@example.com">student</maintainer>
  <license>Apache-2.0</license>
  <buildtool_depend>ament_cmake</buildtool_depend>
  <exec_depend>nav2_bringup</exec_depend>
  <exec_depend>nav2_costmap_2d</exec_depend>
  <exec_depend>tf2_ros</exec_depend>
  <export><build_type>ament_cmake</build_type></export>
</package>
